<a href="https://colab.research.google.com/github/Chimatanagagopal/DEEP-LEARNING_practice/blob/main/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras #library for neural network
import pandas as pd #loading data in table form
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
import numpy as np # linear algebra
from sklearn.preprocessing import normalize # machine learning algorithm library

In [ ]:
data=pd.read_csv("/content/iris.csv")
data.head()


,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [ ]:
data["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
data.loc[data["species"]=="setosa","species"]=0
data.loc[data["species"]=="versicolor","species"]=1
data.loc[data["species"]=="virginica","species"]=2

In [ ]:
data=data.iloc[np.random.permutation(len(data))]
print(data)


     sepal_length  sepal_width  petal_length  petal_width species
17            5.1          3.5           1.4          0.3       0
99            5.7          2.8           4.1          1.3       1
96            5.7          2.9           4.2          1.3       1
61            5.9          3.0           4.2          1.5       1
2             4.7          3.2           1.3          0.2       0
..            ...          ...           ...          ...     ...
127           6.1          3.0           4.9          1.8       2
41            4.5          2.3           1.3          0.3       0
130           7.4          2.8           6.1          1.9       2
95            5.7          3.0           4.2          1.2       1
38            4.4          3.0           1.3          0.2       0

[150 rows x 5 columns]


In [ ]:
X=data.iloc[:,:4].values
y=data.iloc[:,4].values

In [ ]:
X_normalized = normalize(X,axis=0)
print("Examples of X_normalised\n",X_normalized[:3])

Examples of X_normalised
 [[0.07056264 0.09265065 0.02754646 0.01725449]
 [0.07886413 0.07412052 0.08067178 0.07476947]
 [0.07886413 0.07676768 0.08263939 0.07476947]]


In [ ]:
total_length=len(data)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]


In [ ]:
#Neural network module
from keras.models import Sequential
from keras.layers import Dense,Activation
# from keras.utils import np_utils
import tensorflow as tf

In [ ]:
y_train=tf.keras.utils.to_categorical (y_train,num_classes=3)
y_test=tf.keras.utils.to_categorical (y_test,num_classes=3)

In [ ]:
model = Sequential()
model.add(Dense(32,input_dim=4,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(128,activation="relu"))
model.add(Dense(256,activation="relu"))
model.add(Dense(3, activation='softmax'))


/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(loss='categorical_crossentropy',# error
              optimizer='adam',# gradient descent
              metrics=['accuracy'] # accuracy
              )

float64
float64
float64
float64


In [ ]:
model.fit(X_train,y_train,
          validation_data=(X_test,y_test),
          batch_size=30,
          epochs=30)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 87ms/step - accuracy: 0.5750 - loss: 1.0952 - val_accuracy: 0.6667 - val_loss: 1.0903
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8417 - loss: 1.0847 - val_accuracy: 0.6667 - val_loss: 1.0803
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 1.0697 - val_accuracy: 0.9333 - val_loss: 1.0594
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9750 - loss: 1.0482 - val_accuracy: 1.0000 - val_loss: 1.0350
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9583 - loss: 1.0174 - val_accuracy: 1.0000 - val_loss: 0.9964
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9500 - loss: 0.9742 - val_accuracy: 0.9000 - val_loss: 0.9486
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9583 - loss: 0.9158 - val_accuracy: 0.8333 - val_loss: 0.8812
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.8428 - val_accuracy: 0.8000 - val_loss: 0.8060


In [ ]:
prediction=model.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)
accuracy=np.sum(y_label==predict_label)/length * 100
print("Accuracy of the dataset",accuracy )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Accuracy of the dataset 100.0


In [ ]:
correct = np.sum(y_label == predict_label)
wrong = np.sum(y_label != predict_label)

print("Total test data:", length)
print("Correct predictions:", correct)
print("Wrong predictions:", wrong)


print("Accuracy:", correct / length * 100)

Total test data: 30
Correct predictions: 30
Wrong predictions: 0
Accuracy: 100.0
